export enum UserStatusCode {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
  BANNED = 'BANNED',
  PREMIUM = 'PREMIUM',
  VERIFIED = 'VERIFIED',
}
